---
engines:
  trivy:
    enabled: true
    patterns:
      - AVD-DS-0001
      - AVD-DS-0002
      - AVD-DS-0005
      - AVD-DS-0006
      - AVD-DS-0007
      - AVD-DS-0008
      - AVD-DS-0009
      - AVD-DS-0010
      - AVD-DS-0011
      - AVD-DS-0013
      - AVD-DS-0014
      - AVD-DS-0015
      - AVD-DS-0016
      - AVD-DS-0017
      - AVD-DS-0020
      - AVD-DS-0021
      - AVD-DS-0022
      - AVD-DS-0023
      - AVD-DS-0025
      - AVD-DS-0026
      - AVD-KSV-0001
      - AVD-KSV-0003
      - AVD-KSV-0011
      - AVD-KSV-0014
      - AVD-KSV-0016
      - AVD-KSV-0020
      - AVD-KSV-0021
      - HIGH
      - CRITICAL
  eslint:
    enabled: true
  semgrep:
    enabled: true
  secrets:
    enabled: true

ignore:
  - node_modules/**
  - dist/**
  - coverage/**
  - .git/**
